<a href="https://colab.research.google.com/github/kimaelthomas2021/Stats2023/blob/main/ThomasKimael_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#lab3

### Loops

In [5]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


#range of numbers UP TO the number within the parentheses

In [6]:
for i in range(5,8):
    print(i)

5
6
7


#inputting "I" inputs a range of numbers from 5 to 8, not **including** 8

In [7]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


#another ex. 0 to 3, not including 3

### Functions

In [8]:
def square(x):
    return x**2

In [9]:
square(5)

25

#squares whatever is within the parenthesis

In [10]:
square(square(2))

16

#squares the square. 

In [11]:
square(square(square(2)))


256

#triple squares. 2*2=4*4=16*16=256

```
`# This is formatted as code`
```



In [12]:
square(123456)

15241383936

#123456*123456

In [13]:
square(square(5))

625

#5*5=25 *5. this is squaring the square of what is in the parenthesis

In [14]:
def add_two(x):
    return x+2

In [15]:
add_two(5)

7

#adds 2 to what is within the parenthesis 

In [16]:
square(add_two(5))

49

#adds 2 to what is in the parenthesis and then squares it. 5+2=7*7=49

### Logical Branching

In [17]:
choice = "apple"

In [18]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [19]:
choice = "orange"

In [20]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [21]:
choice = "apple"

In [22]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [23]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): mango


In [24]:
choice

'mango'

In [25]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You did not choose apples or oranges.


#### Coins

In [26]:
np.random.random()

NameError: ignored

In [ ]:
np.random.random() > 0.5

In [ ]:
"def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

#if the number is greater than 0.5 than it will be heads, if less than then it will be tails 

In [ ]:
flip_coin()

#this is to flip the coin 

### Graphics Output

In [29]:
from IPython.core.display import display, HTML

In [28]:
display(HTML('<h1>Hello, world!</h1>'))

#inputting html inputs the words or phrase withing the parenthesis

In [30]:
def coin():
  return np.random.randint(2)

#flips the coin so it will land on either heads or tails 

In [34]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

#image of the coin 

In [35]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

#link to image of what should be displayed if the coin lands on heads or tails

In [36]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [37]:
show_img(heads)

#image of heads

In [38]:
show_img(tails)

#image of tails 

In [39]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

#if the coin is within the number of the parentheses it will be considered as head, if not it is considered as "else" and will result in being tails 

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [44]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

# thia is to shuffle the cards within the deck 

In [45]:
a = np.arange(52)

NameError: ignored

#it kept showing an error so i copied directly from your colab and its the same error. however i believe that this is supposed to let the system know how many cards are in the deck.

In [46]:
shuffle(a)

NameError: ignored

In [47]:
np.random.permutation(52)

NameError: ignored

#inputting the amount of cards within the deck. which is 52

### Speed Test

In [50]:
%%timeit
shuffle(a)

NameError: ignored

In [51]:
%%timeit
np.random.permutation(52)

NameError: ignored

In [52]:
import numpy as np

In [53]:
np.random.permutation(52)

array([ 4,  8, 26, 32, 20, 39, 46, 24, 10, 42, 18, 21, 19, 35,  9, 45, 12,
       36, 16, 17, 11, 15, 29, 34, 38, 22, 47, 33, 25, 48, 28,  3, 43, 13,
       31, 44,  2, 49, 23, 14,  6,  7,  5,  1, 37, 27, 41, 40, 50,  0, 30,
       51])

#puts the 52 cards in a random order

In [54]:
cards = np.random.permutation(52)

In [55]:
cards

array([39, 49, 22, 29,  2, 46, 26,  9, 10,  4, 31,  5, 45, 38, 27, 17, 42,
       16,  7, 11, 19, 50, 36, 18, 37, 48, 21, 41,  0, 51,  6, 25, 14, 35,
       12, 32, 23, 15, 33, 43, 34, 47,  8, 13, 24,  3,  1, 40, 28, 30, 20,
       44])

#picks the 52 cards in another random order

In [57]:
cards[0]

39

#gives you the card that is considered as number 0 within the deck

In [58]:
cards[1]

49

#tells you the first card of the deck 

In [59]:
cards[2]

22

#gives the second card of the deck 

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

#the deck of cards 

In [60]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [61]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [62]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [63]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [64]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [65]:
card_name(0)

'Ace of Clubs'

In [66]:

card_name(51)

'King of Diamonds'

In [67]:
cards = np.random.permutation(52)

In [68]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [69]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Five of Clubs', 'Jack of Clubs', 'Seven of Diamonds')

In [70]:
for i in range(5):
    print(card_name(cards[i]))

Five of Clubs
Jack of Clubs
Ten of Hearts
Three of Hearts
Jack of Hearts


In [71]:
for i in range(15):
    print(card_name(cards[i]))

Five of Clubs
Jack of Clubs
Ten of Hearts
Three of Hearts
Jack of Hearts
King of Clubs
Three of Diamonds
Five of Hearts
Six of Clubs
King of Diamonds
Seven of Spades
Three of Spades
Ace of Diamonds
King of Hearts
Four of Clubs


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [72]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [73]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [74]:
i = np.random.randint(4)
j = np.random.randint(13)

In [75]:
i,j

(1, 1)

In [76]:
suit[i]

'p'

In [77]:
card[j]

'2'

In [78]:
from IPython.core.display import display, HTML

In [79]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [80]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [81]:
show_img(img)

In [82]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [83]:
card_image(3)

'k4'

In [85]:
img = card_url_head + card_image(3) + card_url_tail

In [86]:
show_img(img)

In [87]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)